# Generated by Django 5.1.4 on 2026-09-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Repo/live link. Left blank, the frontend falls back to your GitHub profile.')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('labs', 'Labs')], default='shipped', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project tech badges',
                'ordering': ['order', 'id'],
            },
        ),
    ]
