# Generated by Django 5.2.17 on 2026-09-17 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional lucide-react icon name, e.g. "server".', max_length=60),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unchecking hides this skill from the public API.'),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=80, help_text='0-100, used for skill-level indicators.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
