# Generated by Django 5.1.4 on 2026-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('handle', models.CharField(help_text='e.g. "malladiravindra" — used as @handle', max_length=60)),
                ('role', models.CharField(max_length=150)),
                ('role_sub', models.CharField(help_text='e.g. "Python / Django + React / JavaScript"', max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('github_url', models.URLField()),
                ('github_handle', models.CharField(help_text='Display text, e.g. "github.com/handle"', max_length=150)),
                ('linkedin_url', models.URLField()),
                ('linkedin_handle', models.CharField(max_length=150)),
                ('resume_url', models.CharField(default='/resume.pdf', help_text='Path or URL to the resume file the frontend links to.', max_length=300)),
                ('tagline', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
