# Generated by Django 5.2.17 on 2026-09-17 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_seed_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_status',
            field=models.CharField(blank=True, default='Open to opportunities', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='detailed_bio',
            field=models.TextField(blank=True, help_text='Full About-section bio. Separate paragraphs with a blank line.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL/path to a profile photo, if any.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(blank=True, help_text='One or two sentences — used in compact contexts (meta description, cards).', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
