# Generated by Django 5.2.17 on 2026-09-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_profile_availability_status_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_name',
            field=models.CharField(blank=True, help_text='Shorter display form of the name, e.g. "Ravindra Babu" — used in the hero heading and nav logo.', max_length=100),
        ),
    ]
