# Generated by Django 5.2.17 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_profile_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, help_text='Path or URL to a profile photo, if any — e.g. "/profile.jpg".', max_length=300),
        ),
    ]
