# Generated by Django 5.1.4 on 2026-09-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(help_text='Short commit-style hash, e.g. "a1c9f3e"', max_length=12, unique=True)),
                ('type', models.CharField(choices=[('experience', 'Experience'), ('education', 'Education')], max_length=12)),
                ('title', models.CharField(help_text='e.g. "feat: shipped full-stack modules end-to-end"', max_length=200)),
                ('org', models.CharField(help_text='Role/degree + institution', max_length=250)),
                ('meta', models.CharField(help_text='Date range, e.g. "Aug 2024 — Mar 2025"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Timeline entries',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='timeline.timelineentry')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
