# Generated by Django 5.2.17 on 2026-09-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_seed_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='timeline.timelineentry')),
            ],
            options={
                'verbose_name_plural': 'Timeline tech badges',
                'ordering': ['order', 'id'],
            },
        ),
    ]
